# Generated by Django 5.0.4 on 2024-11-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
