# Generated by Django 5.0.4 on 2024-11-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=None, null=True, upload_to='user_pictures/'),
        ),
    ]
