# Generated by Django 5.0.4 on 2024-12-22 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'product'], name='main_favori_user_id_e3c992_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['session_key', 'product'], name='main_favori_session_b88cc9_idx'),
        ),
    ]
