# Generated by Django 5.0.4 on 2024-12-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_favorite_main_favori_user_id_e3c992_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brend',
            name='logo',
            field=models.ImageField(blank=True, default='brend.jpg', null=True, upload_to='brend_logo/'),
        ),
    ]
