# Generated by Django 5.0.4 on 2025-01-02 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_brend_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brend',
            name='logo',
        ),
    ]
